### PR TITLE
Rect

### PR DESCRIPTION
**Pull request by sigvef**
Depends on #15.

### CODE REVIEW

**Comment by stianjensen** [comment]
Does this need a rebase now, or will GitHub handle the duplicate commits?

**Comment by sigvef** [comment]
I think it will handle the commits. We can try merging to find out, and then fix it later if it doesn't work well.

**Comment by stianjensen** [comment]
It worked! \o/

**Comment by sigvef** [comment]
It might not though in the case where commits look the same, but have different hashes because of rebasing. Who knows :P

**Comment by stianjensen** [comment]
Yup, that seems very scary, I'm not even sure I want GitHub to try to handle that case.

**Pull request merged**
